---
services:
  linde_monitor:
    container_name: linde_monitor
    build: .
    environment:
      - VIRTUAL_HOST=linde.lab.gilest.ro
      - VIRTUAL_PORT=8084
    volumes:
      - ./data:/etc/linde
    ports:
      - 8084:8084
    restart: always

networks:
  default:
    name: nginx-proxy
    external: true
